import Head from 'next/head'
import Header from '../components/layout/Header'

import type { AppProps } from 'next/app'

import { client } from '../../client'

import styles from '../styles/App.module.scss'
import layout from '@/styles/layout.module.scss'
import '../styles/globals.scss'


export async function getStaticPaths() {
  const paths = await client.fetch(
    `*[_type == "post" && defined(slug.current)][].slug.current`
  )

  return {
    paths: paths.map((slug: string) => ({ params: { slug } })),
    fallback: true,
  }
}

export default function App({ Component, pageProps }: AppProps) {

  return (
    <>
      <Head>
        <title>Event Espresso</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={layout.full_width}>
        <Component {...pageProps} />
      </main>
    </>
  );
}
