import Head from 'next/head'
import groq from 'groq'
import styles from '@/styles/Home.module.css'

import type { GetStaticProps } from 'next';
import type { HomepageProps } from '../../types';


import { client } from '../../client'

export const getStaticProps: GetStaticProps = async (context) => {
  console.log('%c context', 'color: HotPink;', context);
  const homepage = await client.fetch(
    groq`*[_type == "homepage" ][0]`
  )
  console.log('%c homepage', 'color: Yellow;', homepage);

  return {
    props: {
      homepage
    }
  }
}


const Home: React.FC<HomepageProps> = ({ homepage }) => {
  console.log('%c homepage', 'color: HotPink;', homepage);
  return (
    <>
      <Head>
        <title>Event Espresso</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <h1>Event Espresso</h1>
          <h2>title: {homepage?.title}</h2>
        </div>
      </main>
    </>
  )
}

export default Home;
