import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

import type { GetStaticProps } from 'next';
import type { HomepageProps } from '../../types';


import { client } from '../../client'

const inter = Inter({ subsets: ['latin'] })
console.log('%c inter', 'color: HotPink;', inter);

export const getStaticProps: GetStaticProps = async (context) => {
  console.log('%c context', 'color: HotPink;', context);
  const homepage = await client.fetch(`
    *[_type == "homepage" && slug.current == ""][0]
  `)

  return {
    props: {
      homepage
    }
  }
}


const Home: React.FC<HomepageProps> = ({ homepage }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <h1>{homepage?.slug?.current}</h1>
        </div>
      </main>
    </>
  )
}

export default Home;
